In [17]:
import pandas as pd
file2 = 'preprocessed_cars.csv'
df = pd.read_csv(file2,delimiter=';')

In [18]:
df

,car_name,brand_name,seats,size,fuel_type,transmission_type,rental_company_name,age_req,driving_experice,year,ratings,num_ratings,price,start_date,end_date
0,그랜드스타렉스12인승,현대,12,승합,경유,오토,다움렌트카,26,1,19,3.7,10,15000,2023-07-21,2023-07-22
1,그랜드스타렉스12인승,현대,12,승합,경유,오토,굿모닝렌트카,26,2,18~19,3.4,3,23500,2023-07-21,2023-07-22
2,그랜드스타렉스12인승,현대,12,승합,경유,오토,로그인렌트카,26,2,20,3.6,11,25100,2023-07-21,2023-07-22
3,그랜드스타렉스12인승,현대,12,승합,경유,오토,무지개렌트카,26,2,18~20,4.4,15,29100,2023-07-21,2023-07-22
4,그랜드스타렉스12인승,현대,12,승합,경유,오토,퍼스트렌트카,26,1,19,4.8,6,32600,2023-07-21,2023-07-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137500,제네시스 G90(4WD),현대,5,고급,휘발유,오토,제주OK렌터카,26,1,20,4.2,8,296000,2023-08-18,2023-08-19
137501,카니발 하이리무진 7인승,기아,7,승합,경유,오토,땡큐제주렌트카,26,3,21,4.8,5,306000,2023-08-18,2023-08-19
137502,[수입]22 BMW 420컨버터블,BMW,4,수입,휘발유,오토,제주OK렌터카,26,1,22,4.2,8,341800,2023-08-18,2023-08-19
137503,(캠핑카)코지 560,기아,5,승합,경유,오토,더세븐렌트카,30,2,22,0.0,0,475200,2023-08-18,2023-08-19
137504,(캠핑카)포레스트,현대,4,승합,경유,오토,더세븐렌트카,30,2,22,0.0,0,514800,2023-08-18,2023-08-19

In [8]:
df = df.rename(columns={'check': 'direction'})

In [9]:
labels = ["자린고비", "가성비", "평범", "욜로", "플렉스"]

df_come = df[df['direction'] == 'come'].copy()
df_back = df[df['direction'] == 'back'].copy()

df_come.sort_values('adult_charge', inplace=True)
df_come['금전상황'] = pd.qcut(df_come['adult_charge'], q=5, labels=labels)

df_back.sort_values('adult_charge', inplace=True)
df_back['금전상황'] = pd.qcut(df_back['adult_charge'], q=5, labels=labels)


df_new = pd.concat([df_come, df_back])

df_new.sort_index(inplace=True)

df_new.head()

,name,seat,adult_charge,leavehour,departure,arrival,departure_datetime,arrival_datetime,direction,child_charge,departure_kor,arrival_kor,금전상황
0,에어서울,특가석,35600,6,GMP,CJU,2023-07-21 06:00:00,2023-07-21 07:00:00,come,26700,김포,제주,자린고비
1,에어서울,할인석,47600,6,GMP,CJU,2023-07-21 06:00:00,2023-07-21 07:00:00,come,35700,김포,제주,자린고비
2,에어서울,일반석,119700,6,GMP,CJU,2023-07-21 06:00:00,2023-07-21 07:00:00,come,89775,김포,제주,플렉스
3,진에어,특가석,28200,6,GMP,CJU,2023-07-21 06:05:00,2023-07-21 07:20:00,come,21150,김포,제주,자린고비
4,진에어,할인석,40800,6,GMP,CJU,2023-07-21 06:05:00,2023-07-21 07:20:00,come,30600,김포,제주,자린고비

In [19]:
def safe_qcut(x):
    unique_values = x.nunique()
    if unique_values >= 5:
        return pd.qcut(x, q=5, labels=labels, duplicates='drop')
    else:
        new_labels = labels[:unique_values]
        return pd.qcut(x, q=unique_values, labels=new_labels, duplicates='drop')

# Convert 'start_date' and 'end_date' to datetime
df['start_date'] = pd.to_datetime(df['start_date'])
df['end_date'] = pd.to_datetime(df['end_date'])

# Step 3: Define the labels
labels = ["자린고비", "가성비", "평범", "욜로", "플렉스"]

# Step 4: Apply safe_qcut() to 'price' within each group of 'start_date' and 'end_date'
df['금전상황'] = df.groupby(['start_date', 'end_date'])['price'].transform(safe_qcut)

# Display the first few rows of the dataframe
df

,car_name,brand_name,seats,size,fuel_type,transmission_type,rental_company_name,age_req,driving_experice,year,ratings,num_ratings,price,start_date,end_date,금전상황
0,그랜드스타렉스12인승,현대,12,승합,경유,오토,다움렌트카,26,1,19,3.7,10,15000,2023-07-21,2023-07-22,자린고비
1,그랜드스타렉스12인승,현대,12,승합,경유,오토,굿모닝렌트카,26,2,18~19,3.4,3,23500,2023-07-21,2023-07-22,자린고비
2,그랜드스타렉스12인승,현대,12,승합,경유,오토,로그인렌트카,26,2,20,3.6,11,25100,2023-07-21,2023-07-22,자린고비
3,그랜드스타렉스12인승,현대,12,승합,경유,오토,무지개렌트카,26,2,18~20,4.4,15,29100,2023-07-21,2023-07-22,가성비
4,그랜드스타렉스12인승,현대,12,승합,경유,오토,퍼스트렌트카,26,1,19,4.8,6,32600,2023-07-21,2023-07-22,가성비
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137500,제네시스 G90(4WD),현대,5,고급,휘발유,오토,제주OK렌터카,26,1,20,4.2,8,296000,2023-08-18,2023-08-19,플렉스
137501,카니발 하이리무진 7인승,기아,7,승합,경유,오토,땡큐제주렌트카,26,3,21,4.8,5,306000,2023-08-18,2023-08-19,플렉스
137502,[수입]22 BMW 420컨버터블,BMW,4,수입,휘발유,오토,제주OK렌터카,26,1,22,4.2,8,341800,2023-08-18,2023-08-19,플렉스
137503,(캠핑카)코지 560,기아,5,승합,경유,오토,더세븐렌트카,30,2,22,0.0,0,475200,2023-08-18,2023-08-19,플렉스
137504,(캠핑카)포레스트,현대,4,승합,경유,오토,더세븐렌트카,30,2,22,0.0,0,514800,2023-08-18,2023-08-19,플렉스

In [16]:
df

,car_name,brand_name,seats,size,fuel_type,transmission_type,rental_company_name,age_req,driving_experice,year,ratings,num_ratings,price,start_date,end_date,price_category
0,그랜드스타렉스12인승,현대,12,승합,경유,오토,다움렌트카,26,1,19,3.7,10,15000,2023-07-21,2023-07-22,자린고비
1,그랜드스타렉스12인승,현대,12,승합,경유,오토,굿모닝렌트카,26,2,18~19,3.4,3,23500,2023-07-21,2023-07-22,자린고비
2,그랜드스타렉스12인승,현대,12,승합,경유,오토,로그인렌트카,26,2,20,3.6,11,25100,2023-07-21,2023-07-22,자린고비
3,그랜드스타렉스12인승,현대,12,승합,경유,오토,무지개렌트카,26,2,18~20,4.4,15,29100,2023-07-21,2023-07-22,가성비
4,그랜드스타렉스12인승,현대,12,승합,경유,오토,퍼스트렌트카,26,1,19,4.8,6,32600,2023-07-21,2023-07-22,가성비
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137500,제네시스 G90(4WD),현대,5,고급,휘발유,오토,제주OK렌터카,26,1,20,4.2,8,296000,2023-08-18,2023-08-19,플렉스
137501,카니발 하이리무진 7인승,기아,7,승합,경유,오토,땡큐제주렌트카,26,3,21,4.8,5,306000,2023-08-18,2023-08-19,플렉스
137502,[수입]22 BMW 420컨버터블,BMW,4,수입,휘발유,오토,제주OK렌터카,26,1,22,4.2,8,341800,2023-08-18,2023-08-19,플렉스
137503,(캠핑카)코지 560,기아,5,승합,경유,오토,더세븐렌트카,30,2,22,0.0,0,475200,2023-08-18,2023-08-19,플렉스
137504,(캠핑카)포레스트,현대,4,승합,경유,오토,더세븐렌트카,30,2,22,0.0,0,514800,2023-08-18,2023-08-19,플렉스